name: Reviewpad

on:
  pull_request_target

permissions:
  pull-requests: write
  issues: write

jobs:
  reviewpad_job:
    runs-on: ubuntu-latest
    name: Reviewpad
    steps:
      # Run Reviewpad on all new Issues and Pull Requests! 🦄
      - name: Reviewpad
        uses: reviewpad/action@v3.x
        with:
          # Uses a default Reviewpad configuration file to get your started.
          # For customization and documentation, see https://github.com/reviewpad/action
          file_url: https://github.com/reviewpad/.github/blob/main/reviewpad-models/common.yml
